### ISSUE TITLE
RuntimeError: "nll_loss_out_frame" not implemented for 'Half'

### ISSUE THREAD

**Issue by HeavySnowJakarta** [kaist-dmlab/pcb#3]
When I ran `CUDA_VISIBLE_DEVICES=1 sh scripts/alvlm/main.sh caltech101 vit_b32 random 5732 AS`, it

```
/root/miniconda3/lib/python3.12/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "
Traceback (most recent call last):
  File "/root/pcb/train.py", line 213, in <module>
    main(args)
  File "/root/pcb/train.py", line 156, in main
    trainer.train()
  File "/root/pcb/trainers/alvlm.py", line 492, in train
    self.run_epoch()
  File "/root/pcb/dassl/engine/trainer.py", line 601, in run_epoch
    loss_summary = self.forward_backward(batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pcb/trainers/alvlm.py", line 358, in forward_backward
    loss = F.cross_entropy(output, label)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/functional.py", line 3086, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: "nll_loss_out_frame" not implemented for 'Half'
```

### System info

```
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:46:43) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-124-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 550.120
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.3.0+cu121
[pip3] torchvision==0.18.0+cu121
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.3.0+cu121              pypi_0    pypi
[conda] torchvision               0.18.0+cu121             pypi_0    pypi
        Pillow (10.3.0)
```

really have no idea why the issue happens. hope the info above helps

**Comment by hwany-j** [comment]
First, thank you for your interest in my work. It seems like that your environment does not support the CUDA in pytorch due to version mismatch. 

Could you try to check the `torch.cuda.is_available() == True`? If it is False, you should match the version of CUDA and pytorch. 

Thank you, and sorry for late reply.
